/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesWordleRouteImport } from './routes/games/wordle'
import { Route as GamesWordSearchRouteImport } from './routes/games/word-search'
import { Route as GamesTicTacToeRouteImport } from './routes/games/tic-tac-toe'
import { Route as GamesTetrisRouteImport } from './routes/games/tetris'
import { Route as GamesSudokuRouteImport } from './routes/games/sudoku'
import { Route as GamesSnakeRouteImport } from './routes/games/snake'
import { Route as GamesSlidingPuzzleRouteImport } from './routes/games/sliding-puzzle'
import { Route as GamesMemoryRouteImport } from './routes/games/memory'
import { Route as GamesHangmanRouteImport } from './routes/games/hangman'
import { Route as Games2048RouteImport } from './routes/games/2048'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedModeratorRouteImport } from './routes/_authenticated/moderator'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWordleRoute = GamesWordleRouteImport.update({
  id: '/games/wordle',
  path: '/games/wordle',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWordSearchRoute = GamesWordSearchRouteImport.update({
  id: '/games/word-search',
  path: '/games/word-search',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTicTacToeRoute = GamesTicTacToeRouteImport.update({
  id: '/games/tic-tac-toe',
  path: '/games/tic-tac-toe',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTetrisRoute = GamesTetrisRouteImport.update({
  id: '/games/tetris',
  path: '/games/tetris',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSudokuRoute = GamesSudokuRouteImport.update({
  id: '/games/sudoku',
  path: '/games/sudoku',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSnakeRoute = GamesSnakeRouteImport.update({
  id: '/games/snake',
  path: '/games/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlidingPuzzleRoute = GamesSlidingPuzzleRouteImport.update({
  id: '/games/sliding-puzzle',
  path: '/games/sliding-puzzle',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesMemoryRoute = GamesMemoryRouteImport.update({
  id: '/games/memory',
  path: '/games/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesHangmanRoute = GamesHangmanRouteImport.update({
  id: '/games/hangman',
  path: '/games/hangman',
  getParentRoute: () => rootRouteImport,
} as any)
const Games2048Route = Games2048RouteImport.update({
  id: '/games/2048',
  path: '/games/2048',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModeratorRoute = AuthenticatedModeratorRouteImport.update({
  id: '/moderator',
  path: '/moderator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/moderator': typeof AuthenticatedModeratorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/community/$id': typeof CommunityIdRoute
  '/games/2048': typeof Games2048Route
  '/games/hangman': typeof GamesHangmanRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sliding-puzzle': typeof GamesSlidingPuzzleRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sudoku': typeof GamesSudokuRoute
  '/games/tetris': typeof GamesTetrisRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
  '/games/word-search': typeof GamesWordSearchRoute
  '/games/wordle': typeof GamesWordleRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/moderator': typeof AuthenticatedModeratorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/community/$id': typeof CommunityIdRoute
  '/games/2048': typeof Games2048Route
  '/games/hangman': typeof GamesHangmanRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sliding-puzzle': typeof GamesSlidingPuzzleRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sudoku': typeof GamesSudokuRoute
  '/games/tetris': typeof GamesTetrisRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
  '/games/word-search': typeof GamesWordSearchRoute
  '/games/wordle': typeof GamesWordleRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/_authenticated/moderator': typeof AuthenticatedModeratorRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/community/$id': typeof CommunityIdRoute
  '/games/2048': typeof Games2048Route
  '/games/hangman': typeof GamesHangmanRoute
  '/games/memory': typeof GamesMemoryRoute
  '/games/sliding-puzzle': typeof GamesSlidingPuzzleRoute
  '/games/snake': typeof GamesSnakeRoute
  '/games/sudoku': typeof GamesSudokuRoute
  '/games/tetris': typeof GamesTetrisRoute
  '/games/tic-tac-toe': typeof GamesTicTacToeRoute
  '/games/word-search': typeof GamesWordSearchRoute
  '/games/wordle': typeof GamesWordleRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/leaderboard'
    | '/moderator'
    | '/profile'
    | '/community/$id'
    | '/games/2048'
    | '/games/hangman'
    | '/games/memory'
    | '/games/sliding-puzzle'
    | '/games/snake'
    | '/games/sudoku'
    | '/games/tetris'
    | '/games/tic-tac-toe'
    | '/games/word-search'
    | '/games/wordle'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/leaderboard'
    | '/moderator'
    | '/profile'
    | '/community/$id'
    | '/games/2048'
    | '/games/hangman'
    | '/games/memory'
    | '/games/sliding-puzzle'
    | '/games/snake'
    | '/games/sudoku'
    | '/games/tetris'
    | '/games/tic-tac-toe'
    | '/games/word-search'
    | '/games/wordle'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/community'
    | '/leaderboard'
    | '/_authenticated/moderator'
    | '/_authenticated/profile'
    | '/community/$id'
    | '/games/2048'
    | '/games/hangman'
    | '/games/memory'
    | '/games/sliding-puzzle'
    | '/games/snake'
    | '/games/sudoku'
    | '/games/tetris'
    | '/games/tic-tac-toe'
    | '/games/word-search'
    | '/games/wordle'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  Games2048Route: typeof Games2048Route
  GamesHangmanRoute: typeof GamesHangmanRoute
  GamesMemoryRoute: typeof GamesMemoryRoute
  GamesSlidingPuzzleRoute: typeof GamesSlidingPuzzleRoute
  GamesSnakeRoute: typeof GamesSnakeRoute
  GamesSudokuRoute: typeof GamesSudokuRoute
  GamesTetrisRoute: typeof GamesTetrisRoute
  GamesTicTacToeRoute: typeof GamesTicTacToeRoute
  GamesWordSearchRoute: typeof GamesWordSearchRoute
  GamesWordleRoute: typeof GamesWordleRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/wordle': {
      id: '/games/wordle'
      path: '/games/wordle'
      fullPath: '/games/wordle'
      preLoaderRoute: typeof GamesWordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/word-search': {
      id: '/games/word-search'
      path: '/games/word-search'
      fullPath: '/games/word-search'
      preLoaderRoute: typeof GamesWordSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tic-tac-toe': {
      id: '/games/tic-tac-toe'
      path: '/games/tic-tac-toe'
      fullPath: '/games/tic-tac-toe'
      preLoaderRoute: typeof GamesTicTacToeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/tetris': {
      id: '/games/tetris'
      path: '/games/tetris'
      fullPath: '/games/tetris'
      preLoaderRoute: typeof GamesTetrisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sudoku': {
      id: '/games/sudoku'
      path: '/games/sudoku'
      fullPath: '/games/sudoku'
      preLoaderRoute: typeof GamesSudokuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/snake': {
      id: '/games/snake'
      path: '/games/snake'
      fullPath: '/games/snake'
      preLoaderRoute: typeof GamesSnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/sliding-puzzle': {
      id: '/games/sliding-puzzle'
      path: '/games/sliding-puzzle'
      fullPath: '/games/sliding-puzzle'
      preLoaderRoute: typeof GamesSlidingPuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/memory': {
      id: '/games/memory'
      path: '/games/memory'
      fullPath: '/games/memory'
      preLoaderRoute: typeof GamesMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/hangman': {
      id: '/games/hangman'
      path: '/games/hangman'
      fullPath: '/games/hangman'
      preLoaderRoute: typeof GamesHangmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/2048': {
      id: '/games/2048'
      path: '/games/2048'
      fullPath: '/games/2048'
      preLoaderRoute: typeof Games2048RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/moderator': {
      id: '/_authenticated/moderator'
      path: '/moderator'
      fullPath: '/moderator'
      preLoaderRoute: typeof AuthenticatedModeratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedModeratorRoute: typeof AuthenticatedModeratorRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedModeratorRoute: AuthenticatedModeratorRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  Games2048Route: Games2048Route,
  GamesHangmanRoute: GamesHangmanRoute,
  GamesMemoryRoute: GamesMemoryRoute,
  GamesSlidingPuzzleRoute: GamesSlidingPuzzleRoute,
  GamesSnakeRoute: GamesSnakeRoute,
  GamesSudokuRoute: GamesSudokuRoute,
  GamesTetrisRoute: GamesTetrisRoute,
  GamesTicTacToeRoute: GamesTicTacToeRoute,
  GamesWordSearchRoute: GamesWordSearchRoute,
  GamesWordleRoute: GamesWordleRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
